-- Применить на уже существующей базе (не пересоздаёт таблицу, только добавляет колонки)
ALTER TABLE orders ADD COLUMN IF NOT EXISTS site_favicon_url TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS site_pages INTEGER;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS site_repo TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS bot_username TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS bot_link TEXT;

ALTER TABLE orders ADD COLUMN IF NOT EXISTS status_comment TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS started_at TIMESTAMPTZ;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS done_at TIMESTAMPTZ;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS archived BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE orders ADD COLUMN IF NOT EXISTS paid BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS paid_at TIMESTAMPTZ;

ALTER TABLE orders ADD COLUMN IF NOT EXISTS refund_status TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS refund_amount NUMERIC(10,2);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS refund_comment TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS refund_requested_at TIMESTAMPTZ;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS refund_decided_at TIMESTAMPTZ;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS refunded_at TIMESTAMPTZ;

ALTER TABLE orders ADD COLUMN IF NOT EXISTS support_active BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS support_requested BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS support_tariff TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS support_started_at TIMESTAMPTZ;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS support_expires_at TIMESTAMPTZ;
